// flow-typed signature: 00325d0499b3610740155e7bdc27b109
// flow-typed version: <<STUB>>/@react-native-community/cli_v^3.0.4/flow_v0.104.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-community/cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-native-community/cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-native-community/cli/build/bin' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/bundle/assetPathUtils' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/bundle/buildBundle' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/bundle/bundle' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/bundle/bundleCommandLineArgs' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/bundle/filterPlatformAssetScales' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/bundle/getAssetDestPathAndroid' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/bundle/getAssetDestPathIOS' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/bundle/ramBundle' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/bundle/saveAssets' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/config/config' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/doctor/checkInstallation' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/doctor/doctor' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/doctor/healthchecks/androidHomeEnvVariable' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/doctor/healthchecks/androidNDK' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/doctor/healthchecks/androidSDK' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/doctor/healthchecks/cocoaPods' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/doctor/healthchecks/common' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/doctor/healthchecks' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/doctor/healthchecks/iosDeploy' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/doctor/healthchecks/nodeJS' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/doctor/healthchecks/packageManagers' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/doctor/healthchecks/watchman' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/doctor/healthchecks/xcode' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/doctor' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/doctor/printFixOptions' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/doctor/runAutomaticFix' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/doctor/types' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/doctor/versionRanges' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/info/info' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/init/banner' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/init/editTemplate' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/init/errors/DirectoryAlreadyExistsError' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/init/errors/HelloWorldError' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/init/errors/InvalidNameError' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/init/errors/ReservedNameError' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/init' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/init/init' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/init/initCompat' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/init/printRunInstructions' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/init/template' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/init/templateName' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/init/validate' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/install/install' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/install/uninstall' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/link/getPlatformName' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/link/link' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/link/linkAll' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/link/linkAssets' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/link/linkDependency' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/link/makeHook' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/link/pollParams' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/link/unlink' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/server/copyToClipBoard' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/server/launchDebugger' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/server/launchDefaultBrowser' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/server/launchEditor' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/server/messageSocket' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/server/middleware/copyToClipBoardMiddleware' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/server/middleware/getDevToolsMiddleware' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/server/middleware/getSecurityHeadersMiddleware' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/server/middleware/indexPage' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/server/middleware/loadRawBodyMiddleware' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/server/middleware/MiddlewareManager' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/server/middleware/openStackFrameInEditorMiddleware' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/server/middleware/openURLMiddleware' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/server/middleware/statusPageMiddleware' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/server/middleware/systraceProfileMiddleware' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/server/runServer' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/server/server' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/server/webSocketProxy' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/commands/upgrade/upgrade' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/assertRequiredOptions' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/assign' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/brewInstall' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/config/errors' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/config/findAssets' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/config/findDependencies' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/config/findProjectRoot' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/config' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/config/readConfigFromDisk' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/config/resolveNodeModuleDir' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/config/resolveReactNativePath' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/config/schema' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/copyAndReplace' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/copyFiles' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/envinfo' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/findSymlinkedModules' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/generator/copyProjectTemplateAndReplace' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/generator/promptSync' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/generator/templates' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/gracefulifyFs' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/install' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/installPods' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/loader' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/loadMetroConfig' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/merge' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/packageManager' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/releaseChecker/getLatestRelease' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/releaseChecker' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/releaseChecker/printNewRelease' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/releaseChecker/releaseCacheManager' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/replacePathSepForRegex' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/walk' {
  declare module.exports: any;
}

declare module '@react-native-community/cli/build/tools/yarn' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-native-community/cli/build/bin.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/bin'>;
}
declare module '@react-native-community/cli/build/commands/bundle/assetPathUtils.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/bundle/assetPathUtils'>;
}
declare module '@react-native-community/cli/build/commands/bundle/buildBundle.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/bundle/buildBundle'>;
}
declare module '@react-native-community/cli/build/commands/bundle/bundle.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/bundle/bundle'>;
}
declare module '@react-native-community/cli/build/commands/bundle/bundleCommandLineArgs.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/bundle/bundleCommandLineArgs'>;
}
declare module '@react-native-community/cli/build/commands/bundle/filterPlatformAssetScales.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/bundle/filterPlatformAssetScales'>;
}
declare module '@react-native-community/cli/build/commands/bundle/getAssetDestPathAndroid.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/bundle/getAssetDestPathAndroid'>;
}
declare module '@react-native-community/cli/build/commands/bundle/getAssetDestPathIOS.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/bundle/getAssetDestPathIOS'>;
}
declare module '@react-native-community/cli/build/commands/bundle/ramBundle.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/bundle/ramBundle'>;
}
declare module '@react-native-community/cli/build/commands/bundle/saveAssets.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/bundle/saveAssets'>;
}
declare module '@react-native-community/cli/build/commands/config/config.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/config/config'>;
}
declare module '@react-native-community/cli/build/commands/doctor/checkInstallation.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/doctor/checkInstallation'>;
}
declare module '@react-native-community/cli/build/commands/doctor/doctor.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/doctor/doctor'>;
}
declare module '@react-native-community/cli/build/commands/doctor/healthchecks/androidHomeEnvVariable.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/doctor/healthchecks/androidHomeEnvVariable'>;
}
declare module '@react-native-community/cli/build/commands/doctor/healthchecks/androidNDK.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/doctor/healthchecks/androidNDK'>;
}
declare module '@react-native-community/cli/build/commands/doctor/healthchecks/androidSDK.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/doctor/healthchecks/androidSDK'>;
}
declare module '@react-native-community/cli/build/commands/doctor/healthchecks/cocoaPods.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/doctor/healthchecks/cocoaPods'>;
}
declare module '@react-native-community/cli/build/commands/doctor/healthchecks/common.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/doctor/healthchecks/common'>;
}
declare module '@react-native-community/cli/build/commands/doctor/healthchecks/index' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/doctor/healthchecks'>;
}
declare module '@react-native-community/cli/build/commands/doctor/healthchecks/index.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/doctor/healthchecks'>;
}
declare module '@react-native-community/cli/build/commands/doctor/healthchecks/iosDeploy.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/doctor/healthchecks/iosDeploy'>;
}
declare module '@react-native-community/cli/build/commands/doctor/healthchecks/nodeJS.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/doctor/healthchecks/nodeJS'>;
}
declare module '@react-native-community/cli/build/commands/doctor/healthchecks/packageManagers.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/doctor/healthchecks/packageManagers'>;
}
declare module '@react-native-community/cli/build/commands/doctor/healthchecks/watchman.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/doctor/healthchecks/watchman'>;
}
declare module '@react-native-community/cli/build/commands/doctor/healthchecks/xcode.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/doctor/healthchecks/xcode'>;
}
declare module '@react-native-community/cli/build/commands/doctor/index' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/doctor'>;
}
declare module '@react-native-community/cli/build/commands/doctor/index.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/doctor'>;
}
declare module '@react-native-community/cli/build/commands/doctor/printFixOptions.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/doctor/printFixOptions'>;
}
declare module '@react-native-community/cli/build/commands/doctor/runAutomaticFix.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/doctor/runAutomaticFix'>;
}
declare module '@react-native-community/cli/build/commands/doctor/types.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/doctor/types'>;
}
declare module '@react-native-community/cli/build/commands/doctor/versionRanges.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/doctor/versionRanges'>;
}
declare module '@react-native-community/cli/build/commands/index' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands'>;
}
declare module '@react-native-community/cli/build/commands/index.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands'>;
}
declare module '@react-native-community/cli/build/commands/info/info.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/info/info'>;
}
declare module '@react-native-community/cli/build/commands/init/banner.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/init/banner'>;
}
declare module '@react-native-community/cli/build/commands/init/editTemplate.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/init/editTemplate'>;
}
declare module '@react-native-community/cli/build/commands/init/errors/DirectoryAlreadyExistsError.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/init/errors/DirectoryAlreadyExistsError'>;
}
declare module '@react-native-community/cli/build/commands/init/errors/HelloWorldError.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/init/errors/HelloWorldError'>;
}
declare module '@react-native-community/cli/build/commands/init/errors/InvalidNameError.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/init/errors/InvalidNameError'>;
}
declare module '@react-native-community/cli/build/commands/init/errors/ReservedNameError.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/init/errors/ReservedNameError'>;
}
declare module '@react-native-community/cli/build/commands/init/index' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/init'>;
}
declare module '@react-native-community/cli/build/commands/init/index.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/init'>;
}
declare module '@react-native-community/cli/build/commands/init/init.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/init/init'>;
}
declare module '@react-native-community/cli/build/commands/init/initCompat.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/init/initCompat'>;
}
declare module '@react-native-community/cli/build/commands/init/printRunInstructions.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/init/printRunInstructions'>;
}
declare module '@react-native-community/cli/build/commands/init/template.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/init/template'>;
}
declare module '@react-native-community/cli/build/commands/init/templateName.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/init/templateName'>;
}
declare module '@react-native-community/cli/build/commands/init/validate.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/init/validate'>;
}
declare module '@react-native-community/cli/build/commands/install/install.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/install/install'>;
}
declare module '@react-native-community/cli/build/commands/install/uninstall.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/install/uninstall'>;
}
declare module '@react-native-community/cli/build/commands/link/getPlatformName.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/link/getPlatformName'>;
}
declare module '@react-native-community/cli/build/commands/link/link.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/link/link'>;
}
declare module '@react-native-community/cli/build/commands/link/linkAll.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/link/linkAll'>;
}
declare module '@react-native-community/cli/build/commands/link/linkAssets.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/link/linkAssets'>;
}
declare module '@react-native-community/cli/build/commands/link/linkDependency.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/link/linkDependency'>;
}
declare module '@react-native-community/cli/build/commands/link/makeHook.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/link/makeHook'>;
}
declare module '@react-native-community/cli/build/commands/link/pollParams.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/link/pollParams'>;
}
declare module '@react-native-community/cli/build/commands/link/unlink.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/link/unlink'>;
}
declare module '@react-native-community/cli/build/commands/server/copyToClipBoard.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/server/copyToClipBoard'>;
}
declare module '@react-native-community/cli/build/commands/server/launchDebugger.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/server/launchDebugger'>;
}
declare module '@react-native-community/cli/build/commands/server/launchDefaultBrowser.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/server/launchDefaultBrowser'>;
}
declare module '@react-native-community/cli/build/commands/server/launchEditor.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/server/launchEditor'>;
}
declare module '@react-native-community/cli/build/commands/server/messageSocket.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/server/messageSocket'>;
}
declare module '@react-native-community/cli/build/commands/server/middleware/copyToClipBoardMiddleware.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/server/middleware/copyToClipBoardMiddleware'>;
}
declare module '@react-native-community/cli/build/commands/server/middleware/getDevToolsMiddleware.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/server/middleware/getDevToolsMiddleware'>;
}
declare module '@react-native-community/cli/build/commands/server/middleware/getSecurityHeadersMiddleware.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/server/middleware/getSecurityHeadersMiddleware'>;
}
declare module '@react-native-community/cli/build/commands/server/middleware/indexPage.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/server/middleware/indexPage'>;
}
declare module '@react-native-community/cli/build/commands/server/middleware/loadRawBodyMiddleware.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/server/middleware/loadRawBodyMiddleware'>;
}
declare module '@react-native-community/cli/build/commands/server/middleware/MiddlewareManager.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/server/middleware/MiddlewareManager'>;
}
declare module '@react-native-community/cli/build/commands/server/middleware/openStackFrameInEditorMiddleware.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/server/middleware/openStackFrameInEditorMiddleware'>;
}
declare module '@react-native-community/cli/build/commands/server/middleware/openURLMiddleware.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/server/middleware/openURLMiddleware'>;
}
declare module '@react-native-community/cli/build/commands/server/middleware/statusPageMiddleware.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/server/middleware/statusPageMiddleware'>;
}
declare module '@react-native-community/cli/build/commands/server/middleware/systraceProfileMiddleware.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/server/middleware/systraceProfileMiddleware'>;
}
declare module '@react-native-community/cli/build/commands/server/runServer.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/server/runServer'>;
}
declare module '@react-native-community/cli/build/commands/server/server.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/server/server'>;
}
declare module '@react-native-community/cli/build/commands/server/webSocketProxy.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/server/webSocketProxy'>;
}
declare module '@react-native-community/cli/build/commands/upgrade/upgrade.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/commands/upgrade/upgrade'>;
}
declare module '@react-native-community/cli/build/index' {
  declare module.exports: $Exports<'@react-native-community/cli/build'>;
}
declare module '@react-native-community/cli/build/index.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build'>;
}
declare module '@react-native-community/cli/build/tools/assertRequiredOptions.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/assertRequiredOptions'>;
}
declare module '@react-native-community/cli/build/tools/assign.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/assign'>;
}
declare module '@react-native-community/cli/build/tools/brewInstall.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/brewInstall'>;
}
declare module '@react-native-community/cli/build/tools/config/errors.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/config/errors'>;
}
declare module '@react-native-community/cli/build/tools/config/findAssets.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/config/findAssets'>;
}
declare module '@react-native-community/cli/build/tools/config/findDependencies.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/config/findDependencies'>;
}
declare module '@react-native-community/cli/build/tools/config/findProjectRoot.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/config/findProjectRoot'>;
}
declare module '@react-native-community/cli/build/tools/config/index' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/config'>;
}
declare module '@react-native-community/cli/build/tools/config/index.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/config'>;
}
declare module '@react-native-community/cli/build/tools/config/readConfigFromDisk.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/config/readConfigFromDisk'>;
}
declare module '@react-native-community/cli/build/tools/config/resolveNodeModuleDir.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/config/resolveNodeModuleDir'>;
}
declare module '@react-native-community/cli/build/tools/config/resolveReactNativePath.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/config/resolveReactNativePath'>;
}
declare module '@react-native-community/cli/build/tools/config/schema.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/config/schema'>;
}
declare module '@react-native-community/cli/build/tools/copyAndReplace.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/copyAndReplace'>;
}
declare module '@react-native-community/cli/build/tools/copyFiles.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/copyFiles'>;
}
declare module '@react-native-community/cli/build/tools/envinfo.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/envinfo'>;
}
declare module '@react-native-community/cli/build/tools/findSymlinkedModules.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/findSymlinkedModules'>;
}
declare module '@react-native-community/cli/build/tools/generator/copyProjectTemplateAndReplace.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/generator/copyProjectTemplateAndReplace'>;
}
declare module '@react-native-community/cli/build/tools/generator/promptSync.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/generator/promptSync'>;
}
declare module '@react-native-community/cli/build/tools/generator/templates.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/generator/templates'>;
}
declare module '@react-native-community/cli/build/tools/gracefulifyFs.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/gracefulifyFs'>;
}
declare module '@react-native-community/cli/build/tools/install.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/install'>;
}
declare module '@react-native-community/cli/build/tools/installPods.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/installPods'>;
}
declare module '@react-native-community/cli/build/tools/loader.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/loader'>;
}
declare module '@react-native-community/cli/build/tools/loadMetroConfig.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/loadMetroConfig'>;
}
declare module '@react-native-community/cli/build/tools/merge.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/merge'>;
}
declare module '@react-native-community/cli/build/tools/packageManager.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/packageManager'>;
}
declare module '@react-native-community/cli/build/tools/releaseChecker/getLatestRelease.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/releaseChecker/getLatestRelease'>;
}
declare module '@react-native-community/cli/build/tools/releaseChecker/index' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/releaseChecker'>;
}
declare module '@react-native-community/cli/build/tools/releaseChecker/index.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/releaseChecker'>;
}
declare module '@react-native-community/cli/build/tools/releaseChecker/printNewRelease.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/releaseChecker/printNewRelease'>;
}
declare module '@react-native-community/cli/build/tools/releaseChecker/releaseCacheManager.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/releaseChecker/releaseCacheManager'>;
}
declare module '@react-native-community/cli/build/tools/replacePathSepForRegex.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/replacePathSepForRegex'>;
}
declare module '@react-native-community/cli/build/tools/walk.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/walk'>;
}
declare module '@react-native-community/cli/build/tools/yarn.js' {
  declare module.exports: $Exports<'@react-native-community/cli/build/tools/yarn'>;
}
